services:
  - name: cyberthreatwatch-backend
    type: web
    runtime: docker
    repo: https://github.com/Mrviktur1/cyberthreatwatch-backend
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        sync: false
