services:
  - type: web
    name: cyberthreatwatch-backend
    env: python
    buildCommand: |
      apt-get update && xargs -a apt.txt apt-get install -y
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    plan: free
